### ISSUE TITLE
Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)

### ISSUE THREAD

**Issue by joeybab3** [neonwatty/meme-search#53]
Docker compose for the pro version works great except it can't generate a description for any of the memes. Opening the logs reveals this line when clicking the generate description button:

```
2025-01-20 05:42:53,050 - ERROR - FAILURE: FAILURE: status_sender failed with exception HTTPConnectionPool(host='host.docker.internal', port=3000): Max retries exceeded with url: /image_cores/status_receiver (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x772eec3760c0>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))
2025-01-20 05:42:57,620 - DEBUG - STREAM b'IHDR' 16 13
2025-01-20 05:42:57,621 - DEBUG - STREAM b'IDAT' 41 32768
2025-01-20 05:42:57,622 - INFO - DONE: image loaded --> {image_path}
2025-01-20 05:45:42,117 - INFO - DONE: image encoding complete --> {image_path}
2025-01-20 05:49:10,560 - INFO - DONE: image_to_text extraction of image complete --> /app/public/memes/input/RDT_20240509_1509213134312050392131666.jpg


```

**Comment by joeybab3** [comment]
Seems also like when an image fails to process for description generation it gets stuck in "in queue" without actually being in the queue

**Comment by neonwatty** [comment]
Thanks for the report!

On your first issue:

```
2025-01-20 05:42:53,050 - ERROR - FAILURE: FAILURE: status_sender failed with exception HTTPConnectionPool(host='host.docker.internal', port=3000): Max retries exceeded with url: /image_cores/status_receiver (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x772eec3760c0>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))
```

If you are on Linux it might be that `host.docker.internal` is not defined in your preset set of hosts (like it is - to my understanding - now on mac / windows).

A few things to check:

- the image-to-text container is running on port 3000
- if running on linux - can you try manually adding the internal host by ammending your compose file [as described here](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach/24326540#24326540)?

On your second issue:

```
Seems also like when an image fails to process for description generation it gets stuck in "in queue" without actually being in the queue
```

Great bug find!  Just to triangulate the issue - is this happening on the frontend?

**Comment by joeybab3** [comment]
I will try your hosts suggestion as well as amending the docker-compose file. 

To the second question yes, clicking the button on the frontend causes this.

**Comment by joeybab3** [comment]
Adding that line to my docker compose fixed the other issue. I had to delete the db_data folder in order to remove the tasks stuck as in_progress or removing

**Comment by neonwatty** [comment]
Great!  Added a note to the README.md about the possible `extra_hosts` requirement.  

I'll tag this issue as a `bug` to keep track of the latter issue.

**Comment by neonwatty** [comment]
Addressed with #59

**Comment by kazum1kun** [comment]
Seems like the issue persists with my DSM flavor of Docker. Added the `extra_hosts` line to my `meme_search_pro` service, however I still see the following error on the `image_to_text_generator` 

```
2025-02-09 21:48:42,551 - ERROR - FAILURE: status_sender failed with exception HTTPConnectionPool(host='host.docker.internal', port=2333): Max retries exceeded with url: /image_cores/status_receiver (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f63207887d0>: Failed to resolve 'host.docker.internal' ([Errno -3] Temporary failure in name resolution)")) 
```

**Comment by neonwatty** [comment]
Issue re-opened!  Looks like we need a new default for `DOCKER_HOST_INTERNAL` to cover NAS!

The `DOCKER_HOST_INTERNAL` is just a host IP that allows for intercommunication between containers.

Can you find your NAS's IP and try [setting a custom value](https://github.com/neonwatty/meme-search?tab=readme-ov-file#custom-hosts-and-ports) for `DOCKER_HOST_INTERNAL` in a local `.env` file or directly in the compose file?

**Comment by kazum1kun** [comment]
I switched the `DOCKER_HOST_INTERNAL` to NAS's LAN IP address, and seems like it's working now.

**Comment by neonwatty** [comment]
Fantastic! 

Can you let me know how your experience goes?   Any and all feedback / suggestions would be great so future updates can help better support NAS usage.

The next major update on plate is adding smaller image to text models to lighten the app's footprint and allow for faster processing.

**Comment by kazum1kun** [comment]
Done, see #77

**Comment by neonwatty** [comment]
Closing this as resolved: the original host.docker.internal failure has documented workarounds, the affected NAS setup was confirmed working with a custom host/IP, and the remaining NAS feedback moved to #77.
